# Generated by Django 2.0.3 on 2019-10-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weeb',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=500)),
                ('avatar', models.CharField(max_length=100)),
                ('stats', models.CharField(max_length=255)),
            ],
        ),
    ]
